# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9d58d6c46f2c29aacc7d6e2c25779bbbbe8f7b895d664b45b53c573d6141991146bb760ae2e7783853cfe0d6dbcb4e1e4a9fb24e6b55f9fc1b9c38d528fdec2a

test:
  secret_key_base: 026065227a17c25cad0e89e71f664783eea189d5a550bff89385fb963eced1d0d2808f74a17a75096da5e074839f88a30ce0201016b316c007033fe053566787

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
